# Generated by Django 5.2.8 on 2025-12-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherinfo',
            options={'verbose_name_plural': 'Teacher Info'},
        ),
    ]
