# Generated by Django 5.2.8 on 2025-12-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacherinfo_city_teacherinfo_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='country',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='state',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='zip_code',
        ),
    ]
