# Generated by Django 5.2.8 on 2025-12-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_remove_teacherinfo_city_remove_teacherinfo_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherinfo',
            old_name='address',
            new_name='permanent_address',
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='present_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
