# Generated by Django 5.2.8 on 2025-12-18 04:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_teachernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachernotification',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
