# Generated by Django 5.2.8 on 2025-12-18 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_teachernotification_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachernotification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='teachernotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teachernotification',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='teacher.teacherinfo'),
        ),
    ]
