# Generated by Django 5.2.8 on 2025-12-23 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_alter_teachernotification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachernotification',
            options={},
        ),
        migrations.RemoveField(
            model_name='teachernotification',
            name='is_read',
        ),
        migrations.AlterField(
            model_name='teachernotification',
            name='subject',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='teachernotification',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacherinfo'),
        ),
    ]
