# Generated by Django 5.2.8 on 2025-12-23 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_alter_teachernotification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherinfo',
            options={'verbose_name_plural': 'Teacher'},
        ),
    ]
