# Generated by Django 5.2.8 on 2025-12-23 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_alter_teacherinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachernotification',
            options={'verbose_name_plural': 'Notifications'},
        ),
    ]
