# Generated by Django 5.2.8 on 2026-01-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_teacher_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher_feedback',
            options={'verbose_name_plural': 'Feedback'},
        ),
    ]
