# Generated by Django 5.2.8 on 2026-01-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_alter_teacher_feedback_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher_Feedback',
            new_name='Feedback',
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
    ]
