# Generated by Django 5.2.8 on 2026-01-03 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_rename_teacher_feedback_feedback_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='teacher',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='feedback_entries',
                to='teacher.teacherinfo'
            ),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
