# Generated by Django 5.2.8 on 2026-01-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_rename_feedback_teacher_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at']},
        ),
    ]
