# Generated by Django 5.2.8 on 2026-01-05 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_class_updated_at_section_updated_at_and_more'),
        ('teacher', '0018_attendance_attendancerecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='academic.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('teacher', 'klass', 'section', 'session', 'subject', 'date')},
        ),
    ]
