# Generated by Django 5.2.8 on 2026-01-06 15:32

from django.db import migrations, models


def convert_late_to_absent(apps, schema_editor):
    AttendanceRecord = apps.get_model('teacher', 'AttendanceRecord')
    AttendanceRecord.objects.filter(status='Late').update(status='Absent')


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0019_alter_attendance_unique_together_attendance_subject_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_late_to_absent, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=10),
        ),
    ]
