# Generated by Django 5.2.8 on 2025-12-23 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_adminprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'verbose_name_plural': 'Admin'},
        ),
    ]
