# Generated by Django 5.2.8 on 2025-12-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='roll_no',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Roll Number'),
        ),
    ]
