# Generated by Django 5.2.8 on 2025-12-09 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studentinfo_address_studentinfo_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='address',
        ),
    ]
