# Generated by Django 5.2.8 on 2025-12-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_studentinfo_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='guardian_address',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='guardian_email',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='guardian_phone',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='guardian_relation',
        ),
    ]
