# Generated by Django 5.2.8 on 2025-12-09 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_studentinfo_guardian_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='country',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='state',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='zip_code',
        ),
    ]
