# Generated by Django 5.2.8 on 2025-12-23 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_studentinfo_city_remove_studentinfo_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'ordering': ['session', 'klass', 'section', 'roll_no'], 'verbose_name': 'Student Info', 'verbose_name_plural': 'Student'},
        ),
    ]
