# Generated by Django 5.2.8 on 2026-01-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_studentleave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentleave',
            name='leave_type',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Sick', 'Sick'), ('Annual', 'Annual')], max_length=20),
        ),
    ]
