# Generated by Django 5.2.8 on 2026-01-06 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_class_updated_at_section_updated_at_and_more'),
        ('student', '0012_alter_studentleave_leave_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('Midterm', 'Mid Term'), ('Final', 'Final'), ('Quiz', 'Quiz/Test'), ('Practical', 'Practical'), ('Other', 'Other')], default='Final', max_length=20)),
                ('total_marks', models.DecimalField(decimal_places=2, help_text='Maximum marks for this exam or assessment.', max_digits=6)),
                ('obtained_marks', models.DecimalField(decimal_places=2, help_text='Marks obtained by the student.', max_digits=6)),
                ('grade', models.CharField(blank=True, help_text='Optional grade or letter representation.', max_length=5, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('klass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_results', to='academic.class')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_results', to='academic.section')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_results', to='academic.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='student.studentinfo')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_results', to='academic.subject')),
            ],
            options={
                'verbose_name': 'Student Result',
                'verbose_name_plural': 'Student Results',
                'ordering': ['-recorded_at'],
                'unique_together': {('student', 'subject', 'exam_type', 'session')},
            },
        ),
    ]
